// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIAN224rDUSI8oIe5G4eoOmBvAdHKHKXQ',
    appId: '1:280838117166:web:c12f1ef80bf6ddc1b54cbf',
    messagingSenderId: '280838117166',
    projectId: 'kafecs-gestion',
    authDomain: 'kafecs-gestion.firebaseapp.com',
    storageBucket: 'kafecs-gestion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIHqfYJQyikiMVVSaOkujYHK-kK6xzg5s',
    appId: '1:280838117166:android:b419d7708d0cffabb54cbf',
    messagingSenderId: '280838117166',
    projectId: 'kafecs-gestion',
    storageBucket: 'kafecs-gestion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBTbyWMMO4IfFV6Ze9KKjayKDEdeuusQ',
    appId: '1:280838117166:ios:5f411e1ee48007eeb54cbf',
    messagingSenderId: '280838117166',
    projectId: 'kafecs-gestion',
    storageBucket: 'kafecs-gestion.firebasestorage.app',
    iosBundleId: 'com.example.ewkef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBTbyWMMO4IfFV6Ze9KKjayKDEdeuusQ',
    appId: '1:280838117166:ios:5f411e1ee48007eeb54cbf',
    messagingSenderId: '280838117166',
    projectId: 'kafecs-gestion',
    storageBucket: 'kafecs-gestion.firebasestorage.app',
    iosBundleId: 'com.example.ewkef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIAN224rDUSI8oIe5G4eoOmBvAdHKHKXQ',
    appId: '1:280838117166:web:2f1a92b0309c0da6b54cbf',
    messagingSenderId: '280838117166',
    projectId: 'kafecs-gestion',
    authDomain: 'kafecs-gestion.firebaseapp.com',
    storageBucket: 'kafecs-gestion.firebasestorage.app',
  );
}
